package:
  name: seaborn-minimal
  version: 0.7.1

source:
  fn: seaborn-0.7.1.tar.gz
  url: https://pypi.python.org/packages/ed/dc/f168ff9db34f8c03c568987b4f81603cd3df40dd8043722d526026381a91/seaborn-0.7.1.tar.gz
  md5: ef07e29e0f8a1f2726abe506c1a36e93

requirements:
  build:
    - python
    - pandas
    - matplotlib-minimal
    - scipy
  run:
    - python
    - numpy
    - matplotlib-minimal
    - scipy
    - pandas

test:
  imports:
    - seaborn

about:
  home: http://stanford.edu/~mwaskom/software/seaborn/
  license: BSD
  license_file: LICENSE
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  doc_url: http://stanford.edu/~mwaskom/software/seaborn/
  dev_url: https://github.com/mwaskom/seaborn
